---
title: "Bioinformatics Class 9"
author: "Sarah Wallum"
date: "5/1/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

#Section 1
#Preparing data 
```{r}
url <- "https://bioboot.github.io/bimm143_S18/class-material/WisconsinCancer.csv"
wisc.df <- read.csv(url, sep=",")
wisc.data <- as.matrix(wisc.df[,3:ncol(wisc.df)])
row.names(wisc.data) <- wisc.df$id
#to see diagnoses
table(wisc.df$diagnosis)
#make numeric classification vector 
diagnosis <- as.numeric(wisc.df$diagnosis == "M") 
```

#Exploratory data analysis 
```{r}
#Q1- nrow() to get number of patients, or first column in dim()
dim(wisc.data)
nrow(wisc.data)
#Q2- invert to check & make sure we got them all, value to see the values w/ mean in it 
colnames(wisc.data)
grep("_mean", colnames(wisc.data), value=TRUE)
grep("_mean", colnames(wisc.data), value=TRUE, invert=TRUE)
#Q3
sum(diagnosis)
```

#Section 2
#Performing PCA 
```{r}
#Check column means & standard deviations to see if we need to scale
colMeans(wisc.data)
apply(wisc.data, 2, sd)
#PCA- need to scale; for getting rid of last column could either do 1:30 or -31
wisc.pr <- prcomp(wisc.data[, 1:30], scale=TRUE)
summary(wisc.pr)
#Q4- 44%
#Q5- 3
#Q6- 7
```

#Interpreting PCA results 
```{r}
#Q7- bad plot, hard to see/understand
biplot(wisc.pr)
#Scatter plot observations by components 1 & 2
plot(wisc.pr$x[, c(1,2)], col= (diagnosis + 1), xlab="PC1", ylab="PC2")
#Repeat for components 1 & 3- another way 
plot(wisc.pr$x[,1], wisc.pr$x[,3], col= (diagnosis + 1), xlab="PC1", ylab="PC3")
#Calculate variance of each componenet
pr.var <- wisc.pr$sdev^2
head(pr.var)
#pve= proportion of variance explained
pve <- pr.var / sum(pr.var)
#Scree plot 
barplot(pve, ylab = "Percent of Variance Explained",
     names.arg=paste0("PC",1:length(pve)), las=2, axes = FALSE)
axis(2, at=pve, labels=round(pve,2)*100 )
#Plot cumulative proportion of variance explained
plot(wisc.pr$sdev, xlab = "Principal Component", 
     ylab = "Cumulative Proportion of Variance Explained", 
     ylim = c(0, 1), type = "o")
```

#Selecting number of clusters
```{r}
#scale data 
data.scaled <- scale(wisc.data)
#calculate distance matrix needed for hclust
data.dist <- dist(data.scaled)
#clustering by hclust
wisc.hclust <- hclust(data.dist)
plot(wisc.hclust)
#make tree w/ 4 clusters
wisc.hclust.clusters <- cutree(wisc.hclust, k=4)
#make table
table(wisc.hclust.clusters, diagnosis)
#Q12- cutting w/ different numbers of clusters
wisc.hclust.clusters <- cutree(wisc.hclust, k=8)
table(wisc.hclust.clusters, diagnosis)
```

#Section 4
```{r}
#k means
wisc.km <- kmeans(scale(wisc.data), centers= 2, nstart= 20)
#table
table(wisc.km$cluster, diagnosis)
#compare w/ hclust
table(wisc.hclust.clusters, wisc.km$cluster)
```

#Section 5
```{r}
# Use the distance along the first 7 PCs for clustering 
wisc.pr.hclust <- hclust(dist(wisc.pr$x[, 1:7]), method= "complete")
#Cut into 4 clusters
wisc.pr.hclust.clusters <- cutree(wisc.pr.hclust, k=4)
#Compare to actual diagnoses w/ table 
table(wisc.pr.hclust.clusters, diagnosis)
```

